from File import * 

mafile1 = File(3)

mafile1.afficher()
print(mafile1.fileVide())
mafile1.ajouter(5)
mafile1.afficher()
mafile1.ajouter(10)
mafile1.afficher()
mafile1.ajouter(15)
mafile1.afficher()
mafile1.ajouter(10)
mafile1.afficher()
print(mafile1.filepleine())
print(mafile1.retirer())
mafile1.afficher()
print(mafile1.retirer())
mafile1.afficher()
print(mafile1.retirer())
mafile1.afficher()
print(mafile1.retirer())
mafile1.afficher()
print(mafile1.retirer())
mafile1.afficher()
