animals.pop ()
print( animals ) # deque ([ " cat ", "dog ", "goldfish ", "canary "])
animals.popleft()
print ( animals ) # deque ([ " dog ", "goldfish ", "canary "])
animals.append (" fish ")
print ( animals ) # deque ([ " dog ", "goldfish ", "canary ", "fish "])
animals.appendleft (" horse ")
print ( animals ) # deque ([ " horse ", "dog ", "goldfish ", "canary ", "fish "])
taille = len ( animals )
print ("la␣ taille ␣de␣ deque ␣ animals :␣{}". format ( taille ) ) # la taille de deque
